name: Deploy

# Were we can define the inputs that our action will accept
inputs:
  azure_client_id:
    required: true
  azure_tenant_id:
    required: true
  azure_subscription_id:
    required: true
  azure_container_registry: 
    required: true
  container_name:
    required: true
  resource_group:
    required: true
  cluster_name:
    required: true
  kustomize_path:
    required: true
  namespace:
    required: true

runs:
  using: "composite"
  steps:
    # Checks out the repository this file is in
    - uses: actions/checkout@v3

    # Logs in with your Azure credentials
    - name: Azure login
      uses: azure/login@v1.4.6
      with:
        client-id: ${{ inputs.azure_client_id }}
        tenant-id: ${{ inputs.azure_tenant_id }}
        subscription-id: ${{ inputs.azure_subscription_id }}

    # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
    - name: Get K8s context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ inputs.resource_group }}
        cluster-name: ${{ inputs.cluster_name }}

    # Runs Kustomize to create manifest files
    - name: Bake deployment
      uses: azure/k8s-bake@v2
      with:
        renderEngine: "kustomize"
        kustomizationPath: ${{ inputs.kustomize_path }}
        kubectl-version: latest
      id: bake

    # Deploys application based on manifest files from previous step
    - name: Deploy application
      uses: Azure/k8s-deploy@v4
      with:
        action: deploy
        namespace: ${{ inputs.namespace }}
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          ${{ inputs.azure_container_registry }}/${{ inputs.container_name }}:${{ github.sha }}