apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: your-api-image:latest
        env:
        - name: JWT_TTL
          value: "28800"
        - name: CORS_ALLOW_ORIGIN
          value: "^https://farocity-staging.farosian.com$"
        - name: RESET_URL
          value: "https://farocity-staging.farosian.com/reset-password"
        - name: SERVICE_BUS_QUEUE
          value: "staging"
        - name: SERVICE_BUS_ACTIVE
          value: "true"
        - name: API_ERROR_DEV
          value: "true"
        - name: DEV_MAIL
          value: "true"
        - name: APP_ENV
          value: "dev"
        - name: APP_DEBUG
          value: "1"
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: symfony-secret
              key: app-secret
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: database-url
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: 250m
        volumeMounts:
          - name: log-volume
            mountPath: /var/www/app/var/log
      volumes:
        - name: log-volume
          emptyDir: {}
